sudo: required
language: Cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      # - ubuntu-toolchain-r-test
    packages:
      # - gcc-5
      # - g++-5
      # - clang
      - cmake
      - cmake-data
      - valgrind

before_script:
  - sh ./install_cpputest.sh
  - export CPPUTEST_HOME=/usr/local

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./bin/RunAllTests
