sudo: required
language: Cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
    # - gcc-4.8
    # - g++-4.8
    # - clang
    - valgrind

before_script:
  - sh ./install_cpputest.sh
  - export CPPUTEST_HOME=/usr/local

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./bin/RunAllTests
